### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tomparys** [jlund/docker-chrome-pulseaudio#2]
Hi, could you publish your code under some license so the code can be legally used and changed?

**Comment by jlund** [comment]
Oops! I thought I had already done this. I just added a LICENSE file placing this under the MIT license. Let me know if you do anything cool with it!

**Comment by tomparys** [comment]
Thanks!

I built Skype inside Docker, so thanks for inspiration :)
https://github.com/tomparys/docker-skype-pulseaudio

**Comment by jlund** [comment]
That's awesome!
