### ISSUE TITLE
How to get a public key?

### ISSUE THREAD

**Issue by Sepero** [jlund/docker-chrome-pulseaudio#3]
Without instructions for getting a public key, or at least a link to instructions, this setup is not fool proof. And many fools like myself have no idea where or how to get a public key. Other than that, I really think the Readme directions are very good.

**Comment by jlund** [comment]
Sorry about the delay! I just barely saw this issue. The new README contains the command you need to run if you don't already have an SSH key on your system. Let me know if you have any other questions!

**Comment by Sepero** [comment]
Cheers
